### ISSUE TITLE
[黃俐茹]交作業

### ISSUE THREAD

**Issue by Lillian0614** [kurotanshi/5x-js-201911-homework#10]
作業 repo url: https://github.com/Lillian0614/5x-js-201911-homework

計算機那題, 鍵盤輸入的部分不會~ 所以就pass
然後目前按完等於, 再按其他的符號就會大錯亂 ,這部分還沒處理...

**Comment by kurotanshi** [comment]
嗨，先看樂透題。

雖然題目沒有要求，不過讓使用者 `prompt` 對話框輸入是個友善的做法。

比較可惜的是原本題意要求的是將 `count` 作為參數傳到 `getLottery` 這個 function 中

```
var getLottery = function (count) {
  // 略...
};
```

可是你把 `count` 與迴圈寫在 function 外面了，雖然結果一樣，
比較可惜的是這樣 function 就沒用到 `count` 這個參數了。

這部分可以參考一下前面幾位同學的寫法。

---

再來是計算機。

我有看到你的做法是把所有流程通通塞進 `num` 陣列中，再去解字串用 `eval` 執行。
如果可以的話盡量少用 `eval` 喔，實務上我們用到 `eval` 的機會不多，原因是除了執行效率不好以外，還會有安全性的問題。

如果你想要解決按完等號的其他動作，最簡單的方式就是在計算完之後針對變數做一次 reset ，這樣功能就不會壞掉了。
(不過如果你一開始就點四則運算符同樣會有問題，這也是為什麼不建議用 `eval` 的原因。)

另外，我有看到你嘗試解決小數點誤差，這個很棒。 
我帶了好幾期學生只有你嘗試處理這個。

除了看起來有點暴力的 `Math.round(Number(preaction) * 10000000000) / 10000000000` 寫法之外，

另外，你也可以使用 `toPrecision()` 來將數字改為指定的精確度，並且將結果以字串回傳。
只是單純用來顯示的話，是很實用的方法。

使用方式像這樣：
``` js
var numObj = 5.123456;

numObj.toPrecision();   // 5.123456
numObj.toPrecision(5);  // 5.1235
numObj.toPrecision(2);  // 5.1
numObj.toPrecision(1);  // 5
```


通常浮點數運算的誤差值不會超過 12 位，那麼我們就可以寫成

``` js
$('#result').text(Number(Number(preaction).toPrecision(12)));
```

第一層 Number: `Number(preaction).toPrecision(12)` 是為了將 `preaction` 轉成數字，這樣才有 `toPrecision()` 方法，

第二層 Number 是如果只有 `0` 的情況，會變成 `0.00000000000` ，所以再轉一次 Number 就會變成 `0` 了。

大概是這樣。

---

第三個快閃題，嗯，你的做法滿暴力的，不過有效。 XD

因為例題的結構單純，所以這樣寫執行上沒什麼問題。

不過在 `$("nav")` 的 `click` 你已經透過 `e.stopPropagation();` 阻止了事件傳遞，所以就不用再多下 `$("ul").slideDown(200);` 了喔。

``` js
$("nav").click(function(e){
  e.stopPropagation();
  $("ul").slideDown(200);     // 這行 
});
```
