### ISSUE TITLE
[劉怡蒙]交作業

### ISSUE THREAD

**Issue by dbdlahd1027** [kurotanshi/5x-js-201911-homework#11]
https://codepen.io/evelyn-emo/pen/KKwPWPy?editors=0011

**Comment by kurotanshi** [comment]
嗨，基本的功能都有做出來，不過有個地方需要提醒一下。

預設值的部分，我看到你把運算的數字預設設為 `NaN`

``` js
var firstNum = NaN;
var secondNum = NaN;
```

實務上如果想要表示像這類「空值」的變數，通常會使用 `null` 、 `false` 或是空字串來處理，

因為在比較時有個明確的運算式， `x === null` 、 `x === false` 或 `x === ''` 等，

用 `NaN` 的話，初學者就容易寫成 `n === NaN`，還記得上課曾經講過的，
我們如果要判斷某個東西是不是 `NaN`，是沒辦法用 `==` 或 `===` 來判斷的喔，這點要小心。

在第 20 行的地方就不小心誤用了。
``` js
  if ((firstNum != NaN && secondNumEntered == false && operator != null)){
    secondNumEntered = true;
    $('#result').text($(this).text());
  }
```

其他地方沒有什麼問題，做得很好。
