### ISSUE TITLE
[蔡士民]交作業

### ISSUE THREAD

**Issue by saplingt** [kurotanshi/5x-js-201911-homework#2]
作業 repo url: https://github.com/saplingt/5x-js-201911-homework

lottery:
傳參為空值時卡了, 然後估狗了之後內心發了 "乾...這麼簡單" 的讚嘆聲

calculator:
字串轉為可運算公式時卡了, 但估狗大神解救了我

**Comment by saplingt** [comment]
calculator: 
統一使用jq監聽, 根據老師意見優化 equalCal()

下個目標: 改寫為js

**Comment by kurotanshi** [comment]
嗨，`getLottery` 那題沒什麼問題，在 function 裡面塞預設值除了你的這個寫法：

``` js
var getLottery = function (count) {
  count = count || 1;
  // 略
};
```

之外，在 ES6 也有提供新的寫法：

``` js
var getLottery = function (count = 1) {
  // 略
};
```

這種做法叫 **Default parameters**
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters

但使用時要注意一下瀏覽器的支援度。

---

計算機的部分，原本就沒什麼大問題，就是語法可以更簡潔一些。

像是 event 的 callback function，如果沒有要做其他事的話：

```
$('#equal').on('click', function () {
  equalCal();
})

$('#ac').on('click', function () {
  clear()
})
```

可以寫成：

``` js
$('#equal').on('click', equalCal)

$('#ac').on('click', clear)
```

---

另外，如果遇到多組判斷式，除了用 `if-else` 與 `switch-case` 之外，

可以利用 Object map 的方式，像是:

``` js
function oTurn(o) {
  if (o === '×') {
    return '*';
  } else if (o === '*') {
    return '×';
  } else if (o === '÷') {
    return '/';
  } else if (o === '/') {
    return '÷';
  } else {
    return o;
  }
}
```

可以變成這樣：

```
function oTurn(o) {

  var opMap = {
    '×': '*',
    '*': '×',
    '÷': '/',
    '/': '÷'
  };

  return (o in opMap) ? opMap[o] : o;
}
```

未來只需要針對 `opMap` 這個物件去做擴充即可。

---

把字串轉為算式是個不錯的想法。

可以試著解釋你的 `numCal` 、 `operatorCal` 到 `equalCal` 裡面做了什麼事嗎?

試著把程式碼用白話說出來，有助於你未來與其他成員的溝通喔。

**Comment by saplingt** [comment]
- 快閃題
https://codepen.io/sapling-tsai/pen/ZEYzbpK

想法是點擊 ul 時，防止點擊事件傳遞到 window
```
$("ul").click(function(e){
    e.stopPropagation();
});
```

然後當 ul css display === block 點擊畫 window 收合
```
$(window).click(function(){
   if($("ul").css("display") === "block") {
     $("ul").slideToggle(200);
   }
});
```
