### ISSUE TITLE
[徐韻婷]交作業

### ISSUE THREAD

**Issue by yunhsu473** [kurotanshi/5x-js-201911-homework#3]
老師好~

以防我計算機寫不出來，我先來交樂透作業~
[作業連結](https://github.com/yunhsu473/5x-js-201911-homework)

也因為我不確定樂透作業我寫的是不是老師要的，所以先來確認一下
老師說在 console 印出，所以我就使用了 console.log，但如果老師要的是 return 的話，我就要再研究一下，因為 return 會跳出迴圈~

還有上次的作業我做了一些修正，這裡也附上連結，不好意思再麻煩老師了~
[連結](https://gist.github.com/kurotanshi/c55c94ebcc2475684127029678a3e217)

然後那位交作業的同學也太神了吧QQ 怎麼可以寫那麼快
如果計算機有進度的話會再把作業交上來
謝謝老師~

**Comment by kurotanshi** [comment]
哈囉，印出用 console.log  就可以囉！
如果你要用 return 的話，應該會是二維陣列了。

function 預設值的部分：

``` js
if (n === undefined) {
  n = 1;
}
```

可以寫成

``` js
n = n || 1;
```

或是在宣告時指定:

``` js
var lottery = function (n = 1) { 
// 略... 
}
```

都會有一樣的效果。

上次的作業除了62 行的 function 拼錯導致卡住之外，沒有什麼問題了！

計算機再加油！ 😆

**Comment by yunhsu473** [comment]
老師好~
先道歉，老師對不起我上次居然交了一個壞掉的作業 T T，謝謝老師居然還那麼 nice 確認作業~

交計算機作業：[連結](https://github.com/yunhsu473/5x-js-201911-homework/blob/master/Calculator.html)

有 bug 要先說：
如果連續點擊運算符的話，會直接就顯示上的數字做運算，沒有辦法做到運算符取代的效果
(對不起因為我寫的結構好像沒辦法偵測是否連續點擊運算符捏，如果想到解法再來更新)

我真的寫到懷疑人生 QQQQ
卡到不行的時候我就去估狗一下看看其他人怎麼用 JS 寫計算機，發現大家都用 eval()
我不知道那是甚麼於是就去 MDN 查，然後就看到 MDN 強烈建議 "Never use eval()!"
[MDN連結](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval#Never_use_eval!)

我真是怕爆，於是接受 MDN 的建議，一秒放棄 eval()
然後用把數放進陣列裡再拿出來用的方式計算，真的寫得很卡 ~~
卡到我必須每一個步驟都用備註先寫出來才能寫程式碼，老師覺得傷眼的話真是抱歉惹

還有我真的想不到我 bug 的解法，是不是要重新寫整個結構才能 de 這個 bug 阿 ((崩潰
再麻煩老師了，謝謝 ><

**Comment by kurotanshi** [comment]
哈囉，題目沒有要求要做運算符取代，所以不用擔心 😁

沒有使用 `eval` 這點很棒！ 

因為 `eval` 除了執行效率較差以外，也會有安全性問題，所以能不用就盡量不用。

比對的部分記得用 `===` 取代 `==`，養成良好的習慣。

破框而出的問題雖然題目沒有特別說，不過實務上會盡量用 CSS 來處理，
像 `0.1 + 0.2` 就還是會爆框 XD

功能大致上都有完成了， 倒是可以說說看運算符為什麼想用陣列處理呢？

**Comment by yunhsu473** [comment]
老師好~

關於用陣列處理運算符這回事，請讓我說說我的心路歷程 ><
因為當初是以這個計算機能達到市面上(?)計算機應該要有的功能為目標去做的

所以會以陣列處理運算符是因為想做"做運算後不是點擊 = 而是其他運算符的話，要跑出結果並且繼續運算"
例：直接點擊 2+3-4，中間沒有用=，那計算機就要先將 - 先記錄起來，等運算結果推到 numA 之後，再用 - 來做運算

這樣的話就必須記錄 2 個運算符，所以我才使用陣列

因為我寫這個功能是在寫點擊等於鍵 (equal function) 之前寫的，基本上我剛開始就是以這個功能為目標去寫，所以也可以看到我的 equal function 基本上是根據點擊運算符 (opClick function) 來改

但是如果拿掉這個功能的話，只使用 = 就能達到題目要求的基本運算效果，我應該就不會用陣列~
(有一部份原因也是因為我那時真的寫到懷疑人生，所以在 calArr 寫起來 work 後，我的運算符也選擇用陣列去寫)

還有我也要說明一下我為何是用 == 而不是 === 去寫 
(嗚嗚我想說明我當初是用 ===，真的不是沒有養成用 === 的習慣請原諒我 QAQ)

就是我那時寫的時候因為是要偵測 0 或小數點，但因為我中間把它的值轉來轉去(輸入時是字串，但運算時是數字，在運算過後推回 numA 是數字，但 display 時又是字串)
所以我那時因為懶得判斷是數字還是字串，就用了 == 讓他自動轉型別

也是因為我各種條件是最後面才寫，所以心智已經呈現脆弱狀態
現在看起來我都是用 display 下去做判斷所以應該可以用 [  === 字串] 去做判斷，我之後來改一下好了~

還有我真的沒有想到小數點也會爆框這件事 XD 那時真的寫到覺得自己沒有寫扣的天分很想放棄(邊怨嘆自己的廢邊寫，現在想想有點好笑)，只是想盡可能完善各種功能而已

所以老師說的用 CSS 限制字數是 ```text-overflow:ellipsis;``` 嗎? 
我沒有用過下次可以來用看看

不好意思還要讓老師看我的心路歷程(完全只是自己很想說明)，謝謝老師~~

**Comment by kurotanshi** [comment]
原來如此，如果要做「繼續運算」的話，會變得比較複雜，
如果是邊按邊算是還好，如果要等最後按下 `=` 才計算的話，還會有先乘除後加減的順序問題。

這裡提供你另一個思路，假設使用者依序點擊 `10 + 20 - 3` ，在按下 `-` 號的時候，
是不是可以先把前面的 `10 + 20` 的結果先計算出來，然後再拿這個結果去跟 `- 3` 運算？
這樣也許可以不用以陣列來處理喔。


另外，在字串與數字的轉型，你可以在需要做判別的時候，統一用 `Number()` 或 `String()` 轉成數字或者字串後再用 `===` 比對就好，養成良好的習慣可以減少 bug 出現的機會。
