### ISSUE TITLE
[李玉珊]交作業

### ISSUE THREAD

**Issue by paggieli** [kurotanshi/5x-js-201911-homework#4]
1. 目前完成作業一: 樂透
https://github.com/paggieli/5x-js-201911-homework/blob/master/lottery.html

計算機會再繼續努力,,,

**Comment by kurotanshi** [comment]
Hi, 功能沒有問題！

function 預設值的部分可寫寫成

``` js
count = count || 1;
```

或是 (ES6 Default parameters)
``` js
var getLottery = function (count = 1) {
  // 略
};
```
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters

使用時要注意一下瀏覽器的支援度。

計算機加油！

**Comment by paggieli** [comment]
[快閃題交作業囉~] https://codepen.io/paggieisme/pen/bGGXPYp
卡在不知道怎麼找到除了ul以外的空白處都可以觸發事件找了一下
