### ISSUE TITLE
[劉迦豪]交作業 - 樂透

### ISSUE THREAD

**Issue by Patrick0906** [kurotanshi/5x-js-201911-homework#5]
作業
https://github.com/Patrick0906/5x-js-201911-homework/blob/master/lottery.html

原本卡在 預設（）
但google後解決了

**Comment by kurotanshi** [comment]
功能沒有什麼問題，不過要小心 `var` 不建議寫在 `for` 迴圈內，因為 `var` 宣告的變數作用範圍的最小單位其實是 `function`。

雖然重複 `var` 宣告不會出錯，但是如果要把範圍限制在迴圈內，用 `let` 替代 `var` 會是更好的做法喔。 (原因下次上課會說)
