### ISSUE TITLE
[何敏毓]交作業

### ISSUE THREAD

**Issue by minyumin** [kurotanshi/5x-js-201911-homework#6]
老師果然料事如神，計算機真的大卡關，還好老師佛心讓我們二選一

[樂透]
https://github.com/minyumin/5x-js-201911-homework

雖然預設參數的地方還是小卡關
https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Functions/Default_parameters

**Comment by kurotanshi** [comment]
因為往年有寫出計算機的同學真的不多 XD

預設 count 的部分：
``` js
var count = (typeof count !== 'undefined') ?  count : 1;   
```

除了可以寫成
``` js
count = count || 1 ;
```

還有另一個要注意的地方是，因為  `count` 是從外面傳入的參數，所以內部無需再 `var` 宣告一次喔！
