### ISSUE TITLE
[郭雅華]交作業

### ISSUE THREAD

**Issue by Klas817** [kurotanshi/5x-js-201911-homework#7]
Hi 老師，

repo url: https://github.com/Klas817/5x-js-201911-homework/blob/master/lottery.html

只能先完成樂透，計算機還在燒腦中...

在樂透中對於retrun的使用還不是很能掌握，先用console.log 完成作業。

**Comment by kurotanshi** [comment]
用 `console.log` 就可以了喔！
如果要用 `return` 來做就要變成是二維陣列了。

可以寫成
```
count = count || 1;
```

或是在宣告參數時指定:

``` js
var lottery = function (count = 1) { 
// 略... 
}
```
都可以有一樣的效果

Ref: Default parameters:  https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Functions/Default_parameters
