### ISSUE TITLE
[快閃題] 何敏毓 交作業

### ISSUE THREAD

**Issue by minyumin** [kurotanshi/5x-js-201911-homework#8]
Menu
https://codepen.io/minyumin/pen/JjjgqwO

**Comment by kurotanshi** [comment]
嗨嗨，題目想要的效果是 「點擊選單外任一處會自動收合列表」喔，加油!

**Comment by kurotanshi** [comment]
嗨嗨，題目想要的效果是 「點擊選單外任一處會自動收合列表」喔

效果類似這樣
![menu](https://user-images.githubusercontent.com/362912/69845030-ea6ce700-12a9-11ea-911d-b7597fce3c23.gif)

點擊頭像會彈開 menu，但是點擊外面的時候要被自動關掉。

但是你的文字區塊點擊了也會彈開 menu 喔，再試著修正看看。
加油!

**Comment by minyumin** [comment]
已修正，中午太心急交完作業去吃飯了....

**Comment by kurotanshi** [comment]
嗨，`$(function(){ ... })` 這個是 `$(document).ready({ ... })` 的簡寫法，所以其實只要寫一次就好喔。 像這樣：

``` js
$(function() {

  $("button").click(function(){
    $("ul").slideToggle(200);
  });

  $("body").click(function(){
    $("ul").slideUp(200);
  });

  $("ul, button").click(function(e){
    e.stopPropagation(); //點到連結沒作用(自動收合)
  });

});
```

在實務上，DOM selector 建議以 class + tag name 來取會比較精準，但這是練習就沒什麼關係囉。 另外，除了在目標元素加上 `e.stopPropagation()` ，也可以試著用上課講過的 `e.target` 來作為判斷收合的依據。

速度很快  👍
