### ISSUE TITLE
[快閃題] 劉迦豪 

### ISSUE THREAD

**Issue by Patrick0906** [kurotanshi/5x-js-201911-homework#9]
作業

https://codepen.io/patrick0906/pen/YzPKKwr?editors=1010

**Comment by kurotanshi** [comment]
很棒喔，用 `e.target` 來處理。
但是要注意的是，如果網頁上有其他的 `<li>` 與 `<a>` 標籤的話就會誤判了。

如果可以的話，盡量把條件限縮得精準一點會更好。

**Comment by Patrick0906** [comment]
謝謝老師
已調整為 ('nav li') 與 ('nav a')

**Comment by kurotanshi** [comment]
突然想到有個地方我忘了講
``` js
if($(e.target).is('nav li')||$(e.target).is('nav a')){ 

}
```

可以寫成
``` js
if($(e.target).is('nav li, nav a')){ 

}
```

**Comment by Patrick0906** [comment]
對齁～～～～
